committing latest changes

diff --git a/files/bin/cdnjs-client b/files/bin/cdnjs-client
--- a/files/bin/cdnjs-client
+++ b/files/bin/cdnjs-client
@@ -8,40 +8,14 @@
 # requires: jq, wget
 #
 ##########
-
-conf=$1
-shift
-
+	
 SWITCH="\e["
 NORMAL="${SWITCH}0m"
 YELLOW="${SWITCH}33m"
 RED="${SWITCH}31m"
 GREEN="${SWITCH}32m"
 BLUE="${SWITCH}34m"
-
-if [[ "$1" == "clean" ]]; then
-	locations=$(jq -r -c '.. | select(has("relative-location"?))["relative-location"]' "$conf")
-	oifs=$IFS
-	IFS=$'\n'
-	for d in $locations; do
-		if [[ -d "$d" ]]; then
-			echo -e $BLUE'Cleaning dir '$d'.'$NORMAL
-			rm -Rf "$d"
-		else
-			echo -e $RED'Dir '$d' does not exist.'$NORMAL
-		fi
-	done
-	IFS=$oifs
-	exit $?
-fi
-
-SWITCH="\e["
-NORMAL="${SWITCH}0m"
-YELLOW="${SWITCH}33m"
-RED="${SWITCH}31m"
-GREEN="${SWITCH}32m"
-BLUE="${SWITCH}34m"
-
+	
 function warn {
 	echo -e $YELLOW$@$NORMAL
 }
@@ -141,141 +115,154 @@ function get_css {
 	get $@ "css"
 	return $?
 }
+	
+search-cdnjs (){
+	local results=$(wget -qO- https://api.cdnjs.com/libraries\?search\=$@\&fields\=version,description | jq -r '.results')
+	echo -n $results
+}
 
-tmpdir=$(mktemp -d -t)
-ret=0
-loop=0
-repos=$(jq -r '. as $in| keys[]' $conf)
-for repo in $repos; do
-	cdn=$(jq .$repo $conf)
-	url=$(echo $cdn | jq -r .root)
-	dir=$(echo $cdn | jq -r '.["relative-location"]')
-	deps=$(echo $cdn | jq -r .dependencies)
-	keys=$(echo $deps | jq -r '. as $in| keys[]')
-	if [[ "$loop" != "0" ]]; then
+sync-files () {
+	conf=$1
+	shift
+	
+	tmpdir=$(mktemp -d -t)
+	ret=0
+	loop=0
+	repos=$(jq -r '. as $in| keys[]' $conf)
+	for repo in $repos; do
+		cdn=$(jq .$repo $conf)
+		url=$(echo $cdn | jq -r .root)
+		dir=$(echo $cdn | jq -r '.["relative-location"]')
+		deps=$(echo $cdn | jq -r .dependencies)
+		keys=$(echo $deps | jq -r '. as $in| keys[]')
+		if [[ "$loop" != "0" ]]; then
+			echo -e
+		fi
+		((loop++))
+		green "Repo: $BLUE$repo$NORMAL"
+		green "Url: $BLUE$url$NORMAL"
 		echo -e
-	fi
-	((loop++))
-	green "Repo: $BLUE$repo$NORMAL"
-	green "Url: $BLUE$url$NORMAL"
-	echo -e
-	for d in $keys; do
-		lib=$d
-		part=$(echo $deps | jq -r '.["'$d'"]')
-		version=$(echo $part | jq -r '.["version"]')
-		js=$(echo $part | jq -r '.["js"]?')
-		css=$(echo $part | jq -r '.["css"]?')
-		fonts=$(echo $part | jq -r '.["fonts"]?')
-		locales=$(echo $part | jq -r '.["locales"]?')
-		create_locales_dir=false
-		localesA=
-		if [[ "$locales" == "null" ]]; then
+		for d in $keys; do
+			lib=$d
+			part=$(echo $deps | jq -r '.["'$d'"]')
+			version=$(echo $part | jq -r '.["version"]')
+			js=$(echo $part | jq -r '.["js"]?')
+			css=$(echo $part | jq -r '.["css"]?')
+			fonts=$(echo $part | jq -r '.["fonts"]?')
+			locales=$(echo $part | jq -r '.["locales"]?')
 			create_locales_dir=false
-		else
-			localesAFiles=$(echo $locales | jq -r -c '.. | select(has("file")?)')
-			localesA=$(echo $locales | jq -r '.[] | select( type == "string") ')
-			create_locales_dir=$(echo $part | jq -r '.["create-locales-dir"]?')
-			if [[ "$create_locales_dir" == "null" ]]; then
-				create_locales_dir=true
+			localesA=
+			if [[ "$locales" == "null" ]]; then
+				create_locales_dir=false
+			else
+				localesAFiles=$(echo $locales | jq -r -c '.. | select(has("file")?)')
+				localesA=$(echo $locales | jq -r '.[] | select( type == "string") ')
+				create_locales_dir=$(echo $part | jq -r '.["create-locales-dir"]?')
+				if [[ "$create_locales_dir" == "null" ]]; then
+					create_locales_dir=true
+				fi
 			fi
-		fi
-		create_fonts_dir=false
-		fontsA=
-		if [[ "$fonts" == "null" ]]; then
 			create_fonts_dir=false
-		else
-			fontsAFiles=$(echo $fonts | jq -r -c '.. | select(has("file")?)')
-			fontsA=$(echo $fonts | jq -r '.[] | select( type == "string") ')
-			create_fonts_dir=$(echo $part | jq -r '.["create-fonts-dir"]?')
-			if [[ "$create_fonts_dir" == "null" ]]; then
-				create_fonts_dir=true
+			fontsA=
+			if [[ "$fonts" == "null" ]]; then
+				create_fonts_dir=false
+			else
+				fontsAFiles=$(echo $fonts | jq -r -c '.. | select(has("file")?)')
+				fontsA=$(echo $fonts | jq -r '.[] | select( type == "string") ')
+				create_fonts_dir=$(echo $part | jq -r '.["create-fonts-dir"]?')
+				if [[ "$create_fonts_dir" == "null" ]]; then
+					create_fonts_dir=true
+				fi
 			fi
-		fi
-		create_css_dir=false
-		cssA=
-		if [[ "$css" == "null" ]]; then
 			create_css_dir=false
-		else
-			cssAFiles=$(echo $css | jq -r -c '.. | select(has("file")?)')
-			cssA=$(echo $css | jq -r '.[] | select( type == "string") ')
-			create_css_dir=$(echo $part | jq -r '.["create-css-dir"]?')
-			if [[ "$create_css_dir" == "null" ]]; then
-				create_css_dir=true
+			cssA=
+			if [[ "$css" == "null" ]]; then
+				create_css_dir=false
+			else
+				cssAFiles=$(echo $css | jq -r -c '.. | select(has("file")?)')
+				cssA=$(echo $css | jq -r '.[] | select( type == "string") ')
+				create_css_dir=$(echo $part | jq -r '.["create-css-dir"]?')
+				if [[ "$create_css_dir" == "null" ]]; then
+					create_css_dir=true
+				fi
 			fi
-		fi
-		create_js_dir=false
-		jsA=
-		if [[ "$js" == "null" ]]; then
 			create_js_dir=false
-		else
-			jsAFiles=$(echo $js | jq -r -c '.. | select(has("file")?)')
-			jsA=$(echo $js | jq -r '.[] | select( type == "string") ')
-			create_js_dir=$(echo $part | jq -r '.["create-js-dir"]?')
-			if [[ "$create_js_dir" == "null" ]]; then
-				create_js_dir=true
+			jsA=
+			if [[ "$js" == "null" ]]; then
+				create_js_dir=false
+			else
+				jsAFiles=$(echo $js | jq -r -c '.. | select(has("file")?)')
+				jsA=$(echo $js | jq -r '.[] | select( type == "string") ')
+				create_js_dir=$(echo $part | jq -r '.["create-js-dir"]?')
+				if [[ "$create_js_dir" == "null" ]]; then
+					create_js_dir=true
+				fi
 			fi
-		fi
-		if [[ "" != "$localesAFiles" ]]; then
-			processFiles "$localesAFiles"
-			ret=$?
-		fi
-		if [[ "$ret" != "0" ]]; then
-			break
-		fi
-		if [[ "" != "$fontsAFiles" ]]; then
-			processFiles "$fontsAFiles"
-			ret=$?
-		fi
-		if [[ "$ret" != "0" ]]; then
-			break
-		fi
-		if [[ "" != "$cssAFiles" ]]; then
-			processFiles "$cssAFiles"
-			ret=$?
-		fi
-		if [[ "$ret" != "0" ]]; then
-			break
-		fi
-		if [[ "" != "$jsAFiles" ]]; then
-			processFiles "$jsAFiles"
-			ret=$?
-		fi
-		if [[ "$ret" != "0" ]]; then
-			break
-		fi
-		for _locale in $localesA; do
-			get_locales "$lib" "$version" "$_locale" "$create_locales_dir"
-			ret=$?
+			if [[ "" != "$localesAFiles" ]]; then
+				processFiles "$localesAFiles"
+				ret=$?
+			fi
 			if [[ "$ret" != "0" ]]; then
 				break
 			fi
-		done
-		if [[ "$ret" != "0" ]]; then
-			break
-		fi
-		for _font in $fontsA; do
-			get_fonts "$lib" "$version" "$_font" "$create_fonts_dir"
-			ret=$?
+			if [[ "" != "$fontsAFiles" ]]; then
+				processFiles "$fontsAFiles"
+				ret=$?
+			fi
 			if [[ "$ret" != "0" ]]; then
 				break
 			fi
-		done
-		if [[ "$ret" != "0" ]]; then
-			break
-		fi
-		for _js in $jsA; do
-			get_js "$lib" "$version" "$_js" "$create_js_dir"
-			ret=$?
+			if [[ "" != "$cssAFiles" ]]; then
+				processFiles "$cssAFiles"
+				ret=$?
+			fi
 			if [[ "$ret" != "0" ]]; then
 				break
 			fi
-		done
-		if [[ "$ret" != "0" ]]; then
-			break
-		fi
-		for _css in $cssA; do
-			get_css "$lib" "$version" "$_css" "$create_css_dir"
-			ret=$?
+			if [[ "" != "$jsAFiles" ]]; then
+				processFiles "$jsAFiles"
+				ret=$?
+			fi
+			if [[ "$ret" != "0" ]]; then
+				break
+			fi
+			for _locale in $localesA; do
+				get_locales "$lib" "$version" "$_locale" "$create_locales_dir"
+				ret=$?
+				if [[ "$ret" != "0" ]]; then
+					break
+				fi
+			done
+			if [[ "$ret" != "0" ]]; then
+				break
+			fi
+			for _font in $fontsA; do
+				get_fonts "$lib" "$version" "$_font" "$create_fonts_dir"
+				ret=$?
+				if [[ "$ret" != "0" ]]; then
+					break
+				fi
+			done
+			if [[ "$ret" != "0" ]]; then
+				break
+			fi
+			for _js in $jsA; do
+				get_js "$lib" "$version" "$_js" "$create_js_dir"
+				ret=$?
+				if [[ "$ret" != "0" ]]; then
+					break
+				fi
+			done
+			if [[ "$ret" != "0" ]]; then
+				break
+			fi
+			for _css in $cssA; do
+				get_css "$lib" "$version" "$_css" "$create_css_dir"
+				ret=$?
+				if [[ "$ret" != "0" ]]; then
+					break
+				fi
+			done
 			if [[ "$ret" != "0" ]]; then
 				break
 			fi
@@ -285,19 +272,73 @@ for repo in $repos; do
 		fi
 	done
 	if [[ "$ret" != "0" ]]; then
-		break
-	fi
-done
-if [[ "$ret" != "0" ]]; then
-	error "Exiting with status code $ret"
-	/bin/rm -Rf $tmpdir
-else
-	info "Copying from temp directory $tmpdir"
-	/bin/cp -Rf $tmpdir/* .
-	ret=$?
-	if [[ "$ret" == "0" ]]; then
-		info "Deleting temp directory $tmpdir"
+		error "Exiting with status code $ret"
 		/bin/rm -Rf $tmpdir
+	else
+		info "Copying from temp directory $tmpdir"
+		/bin/cp -Rf $tmpdir/* .
+		ret=$?
+		if [[ "$ret" == "0" ]]; then
+			info "Deleting temp directory $tmpdir"
+			/bin/rm -Rf $tmpdir
+		fi
+	fi
+	return $ret
+}
+clean () {
+	locations=$(jq -r -c '.. | select(has("relative-location"?))["relative-location"]' "$conf")
+	oifs=$IFS
+	IFS=$'\n'
+	for d in $locations; do
+		if [[ -d "$d" ]]; then
+			echo -e $BLUE'Cleaning dir '$d'.'$NORMAL
+			rm -Rf "$d"
+		else
+			echo -e $RED'Dir '$d' does not exist.'$NORMAL
+		fi
+	done
+	IFS=$oifs
+	return $?
+}
+
+
+unset DO_SEARCH DO_CLEAN DO_SYNC
+while [[ $1 ]]; do
+	case "$1" in
+		-S|--search|search|--find|find)     DO_SEARCH=1;;
+		-C|--clean|clean)                   DO_CLEAN=1;;
+		--sync|sync)                        DO_SYNC=1;;
+		*)                                  if [[ "$ARGS" == "" ]]; then ARGS="$1"; else ARGS="$ARGS $1"; fi;
+	esac
+	shift
+done
+
+(( ! DO_SYNC && ! DO_SEARCH && ! DO_CLEAN )) && DO_SYNC=1
+(( DO_SYNC || DO_CLEAN )) && unset DO_SEARCH
+if (( DO_SYNC || DO_CLEAN )) && [[ ! -f "$ARGS" ]]; then
+	error "A cdnjs-client configuration file is required!"
+	exit 1
+fi
+if [[ "$DO_CLEAN" == "1" ]] && [[ -f "$ARGS" ]]; then
+	echo "CLEANING file $ARGS"
+	clean "$ARGS"
+	fret=$?
+	if [[ "$fret" != "0" ]]; then
+		error "Cleaning was not successful"
+		exit $fret
 	fi
 fi
-exit $ret
+if [[ "$DO_SYNC" == "1" ]] && [[ -f "$ARGS" ]]; then
+	echo "SYNCING file $ARGS"
+	sync-files "$ARGS"
+	exit $?
+fi
+(( DO_SEARCH  )) && unset DO_SYNC
+if (( $DO_SEARCH )); then
+	echo "SEARCHING for $ARGS"
+	res=$(search-cdnjs "$ARGS")
+	fret=$?
+	echo $res | jq '.'
+	exit $fret
+fi
+
